=== SangeethRaaj/connectivity/bin/xmls/attd.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="attd">
        <xs:complexType>
            <xs:element name="attd_stat">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="date" type="xs:date"/>
                        <xs:element name="hour">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="7"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="rollno" type="xs:string"/>
                        <xs:element name="status">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="present"/>
                                    <xs:enumeration value="absent"/>
                                    <xs:enumeration value="on-duty"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== SangeethRaaj/connectivity/bin/xmls/attd.xml
<?xml version="1.0"?>
<!DOCTYPE attd SYSTEM "attd.dtd">
<?xml-stylesheet type="text/xsl" href="attd.xsl"?>
<attd xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="attd.xsd">
	<attd_stat>
		<date>18-8-11</date>
		<hour>1</hour>
		<rollno>42</rollno>
		<status>present</status>
	</attd_stat>
	<attd_stat>
		<date>18-8-11</date>
		<hour>1</hour>
		<rollno>43</rollno>
		<status>absent</status>
	</attd_stat>
	<attd_stat>
		<date>18-8-11</date>
		<hour>1</hour>
		<rollno>44</rollno>
		<status>present</status>
	</attd_stat>
	<attd_stat>
		<date>18-8-11</date>
		<hour>2</hour>
		<rollno>42</rollno>
		<status>present</status>
	</attd_stat>
	<attd_stat>
		<date>18-8-11</date>
		<hour>2</hour>
		<rollno>43</rollno>
		<status>present</status>
	</attd_stat>
	<attd_stat>
		<date>18-8-11</date>
		<hour>2</hour>
		<rollno>44</rollno>
		<status>absent</status>
	</attd_stat>
	<attd_stat>
		<date>19-8-11</date>
		<hour>1</hour>
		<rollno>42</rollno>
		<status>absent</status>
	</attd_stat>
	<attd_stat>
		<date>19-8-11</date>
		<hour>1</hour>
		<rollno>43</rollno>
		<status>absent</status>
	</attd_stat>
	<attd_stat>
		<date>19-8-11</date>
		<hour>1</hour>
		<rollno>44</rollno>
		<status>present</status>
	</attd_stat>
	<attd_stat>
		<date>19-8-11</date>
		<hour>2</hour>
		<rollno>42</rollno>
		<status>present</status>
	</attd_stat>
	<attd_stat>
		<date>19-8-11</date>
		<hour>2</hour>
		<rollno>43</rollno>
		<status>absent</status>
	</attd_stat>
	<attd_stat>
		<date>19-8-11</date>
		<hour>2</hour>
		<rollno>44</rollno>
		<status>present</status>
	</attd_stat>
</attd>
