=== SangeethRaaj/connectivity/bin/xmls/class/class.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="classlist">
        <xs:complexType>
            <xs:element name="class">
                <xs:complexType>
                    <xs:all>
					    <xs:element name="ClassId" type="xs.string"/>
                        <xs:element name="UserName" type="emailAddress"/>
                        <xs:element name="Name" type="xs.string"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="emailAddress"> 
        <xs:restriction base="xs:string"> 
            <xs:pattern value="[^@]+@[^\.]+\..+"/> 
        </xs:restriction> 
    </xs:simpleType>
</xs:schema>

=== SangeethRaaj/connectivity/src/xmls/class/classlist.xml
<?xml version="1.0"?>
<!DOCTYPE attd SYSTEM "class.dtd">
<classlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="class.xsd">
    <class>
       <ClassId>C1 </ClassId >
	   <UserName>valli@yahoo.com   </UserName>
	   <Name>CSE   </Name>
    </class>
    <class>
       <ClassId>C2 </ClassId >
	   <UserName> abc@yahoo.com </UserName>
	   <Name>EEE   </Name>
    </class>
	<class>
       <ClassId>C3 </ClassId >
	   <UserName>atoz@gmail.com  </UserName>
	   <Name>Civil   </Name>
    </class>
	<class>
       <ClassId>C1 </ClassId >
	   <UserName>valli@yahoo.com   </UserName>
	   <Name>CSE   </Name>
    </class>
 </classlist>
